spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5439/book
    username: book
    password: book
  jpa:
    show-sql: true

server:
  port: 8088

graphiql:
  enabled: true
  mapping: /graphiql
  endpoint:
    graphql: /api/graphql
